name: insignia_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  logging: ^1.0.2
  image: ^3.1.3
  carousel_slider: ^4.0.0
  flutter_launcher_icons: ^0.9.2
  shared_preferences: ^2.0.13
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  assets:
  - USAF_E2_OR2_AM.png
  - USAF_E3_OR3_AM1.png
  - USAF_E4_OR4_SAM.png
  - USAF_E5_OR5_SSGT.png
  - USAF_E6_OR6_TSGT.png
  - USAF_E7_OR7_MSGT.png
  - USAF_E8_OR8_SMSGT.png
  - USAF_E9_OR9_CCMS.png
  - USAF_E9_OR9_CMSAF.png
  - USAF_E9_OR9_CMSGT.png
  - USA_E2_OR2_PV2.png
  - USA_E3_OR3_PFC.png
  - USA_E4_OR4_CPL.png
  - USA_E4_OR4_SPC.png
  - USA_E5_OR5_SGT.png
  - USA_E6_OR6_SSG.png
  - USA_E7_OR7_SFC.png
  - USA_E8_OR8_1SG.png
  - USA_E8_OR8_MSG.png
  - USA_E9_OR9_CSM.png
  - USA_E9_OR9_SGM.png
  - USA_E9_OR9_SMA.png
  - USA_W1_CW1.png
  - USA_W2_CW2.png
  - USA_W3_CW3.png
  - USA_W4_CW4.png
  - USA_W5_CW5.png
  - USCG_E1_SR.png
  - USCG_E2_AA.png
  - USCG_E2_CA.png
  - USCG_E2_FA.png
  - USCG_E2_SA.png
  - USCG_E3_SM.png
  - USCG_E4_PO3.png
  - USCG_E4_PO3_s.png
  - USCG_E5_PO2.png
  - USCG_E5_PO2_s.png
  - USCG_E6_PO1.png
  - USCG_E6_PO1_s.png
  - USCG_E7_CPO.png
  - USCG_E7_CPO_s.png
  - USCG_E8_SCPO.png
  - USCG_E8_SCPO_s.png
  - USCG_E9_CMC.png
  - USCG_E9_MCPO.png
  - USCG_E9_MCPOCG.png
  - USCG_E9_MCPOCGX.png
  - USCG_E9_MCPOCG_s.png
  - USCG_E9_MCPO_s.png
  - USCG_O10_s.png
  - USCG_O1_s.png
  - USCG_O2_s.png
  - USCG_O3_s.png
  - USCG_O4_s.png
  - USCG_O5_s.png
  - USCG_O6_s.png
  - USCG_O7_s.png
  - USCG_O8_s.png
  - USCG_O9_s.png
  - USCG_W2_CW2_s.png
  - USCG_W3_CW3_s.png
  - USCG_W4_CW4_s.png
  - USMC_E2_PFC.png
  - USMC_E3_LCPL.png
  - USMC_E4_CPL.png
  - USMC_E5_SGT.png
  - USMC_E6_SSGT.png
  - USMC_E7_GSGT.png
  - USMC_E8_1SG.png
  - USMC_E8_MSGT.png
  - USMC_E9_MGSGT.png
  - USMC_E9_SM.png
  - USMC_E9_SMMC.png
  - USMC_W1_WO1.png
  - USMC_W2_CWO2.png
  - USMC_W3_CWO3.png
  - USMC_W4_CWO4.png
  - USMC_W5_CWO5.png
  - USN_E2_SA.png
  - USN_E2_SA_collar.png
  - USN_E3_AM.png
  - USN_E3_CM.png
  - USN_E3_FM.png
  - USN_E3_SM.png
  - USN_E3_SM_collar.png
  - USN_E4_PO3.png
  - USN_E5_PO2.png
  - USN_E6_PO1.png
  - USN_E7_CPO.png
  - USN_E8_CMDCS.png
  - USN_E8_SCPO.png
  - USN_E9_CMCPO.png
  - USN_E9_FMCPO.png
  - USN_E9_MCPO.png
  - USN_E9_MCPON.png
  - USN_O10_s.png
  - USN_O11_s.png
  - USN_O1_s.png
  - USN_O2_s.png
  - USN_O3_s.png
  - USN_O4_s.png
  - USN_O5_s.png
  - USN_O6_s.png
  - USN_O7_s.png
  - USN_O8_s.png
  - USN_O9_s.png
  - USN_SG_AN_s.png
  - USN_SO_OC_s.png
  - USN_W1_WO1_s.png
  - USN_W2_CW2_s.png
  - USN_W3_CW3_s.png
  - USN_W4_CW4_s.png
  - USN_W5_CW5_s.png
  - US_O1.png
  - US_O10.png
  - US_O11.png
  - US_O2.png
  - US_O3.png
  - US_O4.png
  - US_O5.png
  - US_O6.png
  - US_O7.png
  - US_O8.png
  - US_O9.png
  - US_W1_WO1.png
  - US_W2_CW2.png
  - US_W3_CW3.png
  - US_W4_CW4.png
  - US_W5_CW5.png
  - no_insignia.png